import Layout from "@/components/Layout";
import styles from "@/styles/Home/styles.module.css"
import { Text } from "@mantine/core";

const Home = () => {

  return (
    <><Text>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aut enim officia nulla, ratione odit fugit laboriosam aliquid vitae, nemo delectus quidem molestiae ab labore error? Aliquam quas ipsa eos recusandae.
    Cum nam soluta expedita nobis possimus eveniet inventore incidunt. Excepturi incidunt quidem libero rem eum aspernatur! Itaque pariatur vitae quos molestias. Architecto suscipit illo maiores enim iste assumenda animi itaque?
    Laborum, assumenda dolorem dolorum excepturi blanditiis minima dolore ab nesciunt vero. Distinctio aliquid ipsum iste deleniti ad! Illo nulla explicabo voluptatem quisquam at molestias, laudantium dolorem sunt porro vero odio.
    Recusandae maxime nemo labore. Impedit at odit enim sapiente! Quia nihil perferendis quos, incidunt quae eum repudiandae, iure repellat ipsum facere veritatis saepe nam, tenetur voluptate sapiente dolor doloremque at.
    Temporibus optio animi ducimus illo vero non, facilis rerum recusandae totam eum fugit illum iusto vel obcaecati eius voluptas, labore similique laborum maiores? Voluptates, in ipsa modi ut quaerat unde?
    Placeat accusamus, sapiente suscipit animi minus tempora ad quae architecto recusandae nisi obcaecati iusto vero facilis sed molestiae ea magni quisquam. Maxime officiis, magni quas voluptate reiciendis vitae architecto enim!
    Earum recusandae illum distinctio doloremque nostrum totam perspiciatis commodi quis autem ipsum nesciunt necessitatibus vitae officia debitis officiis accusantium, laborum esse praesentium optio dolorem aliquam expedita doloribus reprehenderit tempora? Nihil!
    Dignissimos laborum mollitia dolorum! Repellendus nam minus, tempora quos officiis consequatur neque laborum harum qui recusandae laboriosam ullam sit incidunt dicta sint voluptatum. Laboriosam optio aperiam, consequatur excepturi id quam?
    Nostrum voluptas repellendus aperiam impedit quam itaque doloribus nihil similique dignissimos, ratione fuga accusamus officia ea quaerat, asperiores cupiditate sint! Sit eaque tempora quia qui dicta, modi blanditiis architecto tempore!
    At, ad? Sed consectetur similique natus, laboriosam possimus vitae mollitia odio obcaecati doloremque, reprehenderit quaerat harum. Reprehenderit, earum nesciunt quod ea, iusto similique molestiae, mollitia eius impedit nisi odit sunt.
    Beatae, repellendus at inventore, repellat ullam praesentium, molestiae modi dignissimos porro aspernatur eveniet sequi voluptas pariatur. Quisquam, aperiam. Possimus officiis quisquam nisi ut. Nam iure, porro repellat quod illo eaque?
    Doloremque dolore, deleniti sit illum a veritatis rem voluptate harum? Nulla, atque! Eius iste aspernatur laborum, dolor velit iure autem debitis saepe repudiandae. Veniam aperiam voluptates eveniet, debitis quaerat numquam?
    Nobis sint molestiae totam saepe eius? Molestiae, officia quia. Ea ipsa nobis minus et perferendis, repellat commodi voluptate vero magnam? Voluptatibus reprehenderit maiores distinctio. Ipsum possimus minus cupiditate eum eligendi.
    Hic magnam voluptatem cumque alias tenetur laudantium quia obcaecati nemo molestiae odit saepe nam cupiditate omnis inventore blanditiis distinctio dolores numquam, mollitia vero odio ipsam. Delectus in vel libero nihil?
    Quam sed ratione voluptatibus expedita. Quaerat autem velit accusamus rem quos reiciendis laboriosam numquam, ea, deleniti voluptas aspernatur magnam omnis eveniet ratione laborum fugiat voluptates cum aperiam. Omnis, dignissimos officiis!
    Earum numquam tempore nihil. Fugiat eveniet ipsam atque optio, vero, incidunt dolore, rerum consequatur perferendis laborum earum sequi nemo labore. Dolorum adipisci omnis fuga commodi est neque maxime porro incidunt.
    Quas exercitationem, quidem nesciunt totam, sit numquam, magnam voluptatum accusamus distinctio nobis voluptate provident. Sapiente ipsa a voluptates, fugiat ab tempore accusamus labore esse corporis quis deserunt totam aut fugit.
    Pariatur reiciendis itaque architecto labore accusamus, illo aspernatur beatae commodi tempora qui nulla in quia fugit culpa ut nemo sequi fugiat officiis minus voluptatem aperiam voluptatum excepturi? Et, ex incidunt.
    Eius officia eligendi nihil, est optio numquam excepturi ipsa a architecto provident quae sapiente. Beatae nisi accusamus impedit dolor. Illum tempore at nihil sapiente qui debitis, ipsam eligendi impedit aliquam.
    Obcaecati a vel, minima quibusdam accusantium inventore id ipsam voluptatum, rem accusamus necessitatibus illo nulla dolores unde nam sed quidem esse velit? Laborum, perferendis fuga! Aperiam corporis ab reiciendis dignissimos.
    Vitae modi impedit ducimus sint, labore eaque provident accusamus. Voluptas praesentium iusto doloremque repudiandae quaerat voluptates voluptatum libero perferendis tenetur? Aspernatur alias perferendis nulla hic minus iure ullam voluptatem deserunt?
    Deleniti ex eveniet deserunt nam accusamus. Similique a fugit ducimus debitis quaerat nobis esse, dicta ab provident? Dolores dolore doloribus minima quasi tempore repudiandae accusamus explicabo. Eaque eveniet magni illo!
    Harum itaque quod, quas nulla, repudiandae doloremque magni veniam porro libero, ea sapiente ratione ut. Sunt sapiente libero accusantium rerum vitae totam earum quae officiis? Exercitationem illo voluptas corporis enim!
    Non harum ut esse eum vel cupiditate perferendis? Ut architecto consequuntur sint unde. Ullam, deserunt reprehenderit placeat iste officia facere quasi inventore modi sed ea in cum. Temporibus, asperiores rerum!
    Nulla possimus similique illo recusandae nobis quos numquam? Modi, officia molestias consequatur nemo vitae magni atque praesentium non culpa tempora consectetur voluptatum accusamus, minus repellendus suscipit deserunt mollitia. Velit, nesciunt!
    Voluptatibus illo non, ex possimus deserunt, quod nihil exercitationem temporibus totam tempore dicta molestiae veniam ea? Dolore, minima culpa beatae dicta, aliquid quas, maxime tempora nisi cumque rerum eius in.
    Et quam, iure obcaecati ab accusamus iusto at nisi quos quisquam facere ratione, eius ullam eos praesentium recusandae error numquam saepe delectus perspiciatis commodi! Recusandae asperiores voluptatibus repudiandae voluptatum dicta.
    Deleniti voluptas laudantium illum minus necessitatibus, illo iusto totam dolorem voluptatibus, adipisci vitae porro eveniet consequatur recusandae. Blanditiis magni dolor, saepe pariatur est laborum corrupti assumenda, nisi quae necessitatibus possimus.
    Minima quis similique veritatis? Sed nemo laborum et, iste enim dolores quae, assumenda fugit placeat asperiores quidem deleniti illum, veritatis quo possimus neque quam totam veniam sint. Nesciunt, officiis provident!
    Similique id aut illo numquam quo mollitia modi, autem officiis odio beatae doloribus architecto a minima labore voluptas nihil eaque iure nesciunt et. Illo laudantium praesentium nihil, pariatur quam saepe?
    Quam doloremque dolores fuga esse accusantium, ullam numquam rem temporibus! Nihil dolorum debitis culpa provident dolorem, neque quidem esse illum optio sequi deleniti consectetur dolores consequatur nemo aspernatur porro aut.
    Ipsum totam nam delectus dolorem illo modi recusandae consectetur ducimus reprehenderit ad vero facilis sint aliquam neque, hic iste nostrum quas, et aspernatur fuga velit esse aperiam! Similique, ut architecto?
    Quo dolores numquam ad at asperiores iure deserunt itaque eaque, voluptatibus qui? Perferendis, quod aspernatur officiis itaque recusandae maiores optio ipsa consequuntur illo inventore ratione labore dolores, saepe cum autem.
    Enim vitae vero natus quae facilis, officiis quia. Minus fugiat earum maiores vel expedita, minima ab animi perferendis provident, sint ipsa molestiae ad. Amet iure minus magnam blanditiis aut eius.
    Numquam totam ex tempora dolores expedita, nemo eligendi repudiandae enim reiciendis accusantium? Amet labore repudiandae consequatur ea maiores saepe quis eveniet, nostrum corporis, praesentium temporibus ducimus nulla delectus laborum? Maxime.
    Doloremque earum, natus inventore molestiae mollitia adipisci non iste. Voluptatibus iusto molestiae sit, a recusandae id amet! Fugiat adipisci nam autem rem nihil, molestias saepe cumque enim, rerum culpa laudantium.
    Quos, nam odio? Recusandae obcaecati eum impedit repellendus deserunt dolor animi dignissimos ipsum molestiae, saepe assumenda eaque non officia, earum mollitia, sunt nostrum quisquam cum sit explicabo quos esse tempore.
    Magni, porro aut nesciunt voluptatibus numquam adipisci accusantium unde sint explicabo recusandae obcaecati labore est similique quaerat minima architecto harum laborum dolor voluptatem et? Ratione, illo? Ut sint impedit omnis.
    Excepturi labore beatae ex nam pariatur, at tempora officiis nihil porro magni aperiam, id adipisci facere tempore provident ratione quos omnis tenetur natus deleniti praesentium quae. Sed incidunt quae assumenda.
    Libero non magnam neque totam error aperiam distinctio molestias quae? Ipsa dolores, sit, dolor nihil ea adipisci blanditiis, recusandae maxime consequuntur architecto corporis necessitatibus reiciendis tempora unde non repudiandae quo?
    Debitis architecto totam recusandae quis quam dolore assumenda dolorum eos! Natus distinctio cupiditate maxime corporis nihil quis iure rerum delectus? Excepturi ut suscipit aliquam ad quia accusantium sed voluptatum vero?
    Cupiditate illum perferendis laudantium, quidem voluptas animi minus provident ducimus asperiores dignissimos, placeat iusto nesciunt tempora laboriosam harum, iste aliquam aspernatur sed nemo! Eum incidunt ullam tempora beatae. Corrupti, veritatis!
    Optio a, quod quos qui cupiditate neque, quas eveniet labore quam quia fugit, voluptatem esse porro impedit repellendus accusamus. A dolorem impedit ab minima est iste aliquam distinctio et deserunt!
    Dicta amet praesentium asperiores iste rerum nihil facilis facere, provident veniam, accusamus repellat cupiditate fuga sit consequuntur dolore eius laudantium quasi totam ad quidem dignissimos optio maiores eligendi cum? Est.
    Delectus enim, tenetur ab quasi iure ut provident odit modi. Officia dolorem earum, minus soluta fuga voluptatum a natus reiciendis consequatur ab omnis dignissimos quasi ex, ad consectetur deleniti perferendis!
    Numquam quasi corporis architecto molestiae tenetur voluptatum tempora ipsam, cumque dolor voluptas, est quisquam accusantium, ad ratione? Odio ipsa qui facere consectetur? Porro optio non quidem repudiandae sapiente maxime animi?
    Mollitia omnis magnam sint culpa eius. Tempora quam praesentium hic quia totam, odio animi quidem voluptates amet nesciunt molestias debitis illum dolore voluptatibus error, vero qui atque commodi fugit maiores.
    Animi, optio sit. Eaque sit repudiandae soluta neque incidunt ratione exercitationem asperiores libero, id molestias suscipit ex dolor reprehenderit corporis, adipisci aspernatur at ut, ad rerum fuga nesciunt. In, labore!
    Accusantium, deleniti inventore commodi illum dicta vero consectetur odio maxime natus enim quos autem, sunt rem quam aliquam labore officiis? Animi aspernatur similique, corporis minus accusamus nulla? Adipisci, unde sed.
    Ducimus iusto repudiandae dolores at aut impedit! Earum minus at dolorem, dolore ipsam pariatur eveniet veniam harum culpa distinctio. Voluptatibus provident aliquid obcaecati optio corporis velit debitis facere id rem!
    Officia quibusdam aut dolorum, voluptatibus dignissimos voluptate repellendus debitis delectus libero nulla? Velit, consectetur quidem. Odit totam blanditiis doloribus ipsa officia rem eaque, itaque, tempora aliquam distinctio facere assumenda voluptatum.
    Praesentium qui, assumenda pariatur ut dolore perspiciatis, non excepturi unde eos earum repellendus atque dicta iste aperiam nisi ab distinctio fugiat modi quis laudantium. Sequi doloremque beatae corporis provident natus!
    Nostrum repellat doloribus deleniti dicta pariatur itaque autem, rerum animi laboriosam quam optio, nesciunt, necessitatibus nulla ipsam odit. Explicabo dolor in repellendus, asperiores repudiandae esse necessitatibus laborum sed quam deleniti.
    Praesentium recusandae molestias magni hic blanditiis provident sequi odio laboriosam quod laborum corrupti iusto soluta placeat nam ipsa, aliquam, ipsum fugiat adipisci tempora, non aspernatur harum consectetur. Voluptatum, modi fuga!
    Eos odit similique quae est, excepturi doloremque quaerat iusto impedit commodi enim, sapiente sit! Voluptates, non quos debitis assumenda placeat omnis animi reiciendis, odio temporibus exercitationem magnam commodi architecto officia?
    Nobis quo reprehenderit ex aperiam facere veritatis asperiores placeat libero quasi consequuntur? Vitae nemo alias, omnis, reprehenderit quisquam aliquam amet aperiam vel deserunt veritatis possimus sint fugit rerum facere architecto!
    Dolorum, velit maxime cumque architecto voluptates voluptate, blanditiis voluptatibus modi incidunt non possimus repellat officiis similique est. Cupiditate ratione provident dolor? Fugit maxime inventore repudiandae ducimus tempora eligendi perferendis quisquam.
    Porro error nisi corporis reprehenderit et praesentium nobis velit. Cum provident assumenda, dolorum soluta culpa deserunt beatae blanditiis qui aut maiores asperiores, saepe facere. Suscipit amet autem harum quae magnam!
    Ex omnis illo velit harum incidunt ullam, architecto, ipsam dolor, accusantium culpa voluptate earum officia vel sapiente nulla exercitationem adipisci laudantium similique. Ex harum iste sequi sit aliquid, unde nulla.
    Magnam dolore officia laudantium amet sed quaerat ad, quibusdam earum, at rem error velit impedit maxime quia commodi placeat perspiciatis necessitatibus. Corporis ab consequuntur, expedita sequi architecto laborum totam eveniet.
    Alias, eveniet quaerat molestiae voluptas in minima totam ex earum illo! Suscipit officia recusandae rerum ipsam beatae nemo tempora molestias fugiat doloremque a! Optio, quasi? Quis nisi doloremque reprehenderit reiciendis.
    A nesciunt ut sequi ea culpa rerum fugiat impedit excepturi reprehenderit, voluptates doloremque quae? Provident aut, debitis minus beatae in animi qui molestias itaque ullam excepturi? Placeat, expedita. Exercitationem, possimus?
    Quas iure, nulla eos asperiores et perspiciatis eligendi a sit quisquam, corrupti inventore ipsam facere nihil tenetur, odit maxime quaerat culpa deleniti saepe quasi consequuntur! Itaque laboriosam molestiae debitis rerum?
    Architecto fuga, voluptate repellendus rerum delectus voluptates est cupiditate quia tempore consequuntur, obcaecati dignissimos quam officia nihil provident sunt doloribus id asperiores alias ab dolorem nobis neque non debitis. Atque.
    Veritatis quaerat ipsam, facere pariatur, ut fugiat recusandae quasi error hic velit commodi. Perferendis est aliquid dolorem, rerum necessitatibus iure, eius sit libero molestias dolores, natus doloremque nemo facere odio.
    Blanditiis impedit delectus velit reiciendis! Officiis repudiandae minus atque odit eos quas nostrum molestiae unde modi consequuntur harum culpa excepturi error quidem autem in nulla sed, nam magnam fuga id.
    Tenetur, illo. Cumque praesentium quae rem atque numquam doloribus laudantium, tempora ut ducimus maiores repudiandae, porro nemo consectetur soluta voluptas, molestias laboriosam possimus temporibus? Cum alias ad veniam voluptates molestiae!
    Autem tempora nostrum recusandae ad voluptas assumenda dicta vel totam adipisci maiores minus eius, mollitia hic obcaecati quam reprehenderit beatae omnis? Possimus, provident perferendis! Repudiandae commodi possimus architecto odit distinctio?
    Hic vel rerum magni nisi libero voluptatem odio voluptatum repudiandae voluptas adipisci repellendus, possimus nam dolorem veniam praesentium totam beatae explicabo corporis ipsam ea numquam vero maxime! Corrupti, eveniet. Optio.
    Vero sint illo harum molestiae, labore aut, earum, asperiores nisi aliquid nesciunt totam consequuntur accusantium est recusandae! Magnam, facilis. Itaque nihil accusantium magnam ex tempore. Nihil assumenda quod sed dolorum?
    Excepturi veritatis debitis asperiores sit dignissimos, possimus ipsum, itaque totam nemo rem pariatur perspiciatis amet esse ducimus tempora cumque commodi. Magnam quod cum illum id eius adipisci ducimus! Cumque, at!
    Odio quasi nihil fugit ab, accusantium eius alias atque minima officiis placeat numquam non aut, architecto qui expedita suscipit quis, totam commodi adipisci magni debitis exercitationem esse sed. Minus, temporibus.
    Cumque eos minima laborum obcaecati, iusto consequuntur vel praesentium molestiae, repudiandae nobis quo, recusandae aspernatur. Recusandae culpa at nihil deleniti quaerat, ipsa excepturi mollitia voluptates ipsam laborum eligendi, autem provident!
    Sapiente aperiam nobis minima explicabo optio unde ut eligendi ad illum, odit incidunt, at voluptas a ratione vitae deleniti eaque adipisci recusandae eius? Quaerat optio architecto voluptatem, adipisci quae soluta.
    Exercitationem minus tempora dolores odit quaerat officiis ipsa facilis error sit esse nulla a culpa, nisi iure saepe similique quod illo, quo, ex cumque dolorum maiores suscipit. Assumenda, iusto nam!
    Voluptas laboriosam, cumque odit soluta explicabo iusto nemo aperiam assumenda, consequuntur consectetur maxime sunt adipisci. Blanditiis corporis possimus explicabo quam, fuga ducimus beatae autem, dignissimos velit labore hic odit dicta?
    Deleniti repellendus quasi minima, eius dicta molestias molestiae ea numquam enim corporis nobis labore voluptate architecto sit nemo ipsum iure at atque amet esse ipsam omnis. Earum aperiam mollitia accusantium.
    Labore, doloremque fugiat aut veniam enim consequuntur blanditiis quia laborum vel? Hic omnis itaque odit cum quaerat ex qui illo possimus, doloribus, blanditiis optio inventore nam labore at, eaque ullam!
    Molestias ipsa molestiae, cumque enim quos quas culpa sit necessitatibus facere debitis ducimus aspernatur fugit, itaque doloremque dicta facilis nihil voluptates placeat, at laboriosam. Quo aspernatur error facere non earum.
    Exercitationem asperiores molestiae recusandae quibusdam alias hic beatae? Quidem, tenetur, facere ipsam quasi sint possimus eveniet in commodi, quis nulla consectetur quibusdam ratione provident repellendus magni dolorum sapiente! Saepe, quisquam!
    Nihil iure, itaque vel aspernatur laboriosam repellat consequuntur corrupti ipsum sequi distinctio unde culpa incidunt accusantium quia modi. Aspernatur ut similique eaque? Minus voluptate labore quidem, quibusdam a commodi quaerat.
    Qui ex earum aperiam fugit ad consequuntur repellendus aspernatur culpa. Laborum dolores esse natus tenetur, molestiae accusantium doloremque ducimus cumque ut quis, obcaecati inventore! Ad laborum quibusdam incidunt amet accusamus.
    Placeat sunt officia quos inventore dolores sint iure recusandae laborum cumque blanditiis eligendi dolore expedita in, magni maiores atque assumenda maxime illum minima voluptatem alias voluptates debitis. Ullam, cum natus!
    Non officia eveniet facere quas eos dolorem vel nobis ab, dicta optio, cum vitae pariatur. Adipisci ad ullam harum neque deserunt esse doloribus cumque dolorem, quod consequatur quo nobis optio!
    Aliquid iste quasi beatae asperiores doloribus ab? Quae dolorum ab minima exercitationem est vero molestiae, voluptatem odit atque veniam? Officiis mollitia voluptatem nesciunt, ipsum praesentium dolor qui reiciendis dolore non.
    Magni facilis unde tempore deleniti rem obcaecati amet, illo quaerat ducimus praesentium, maiores perferendis! Fugit, labore temporibus saepe praesentium fugiat explicabo unde quo. Unde, odio soluta. Mollitia nostrum quae quod.
    Veniam officia dolorum possimus voluptate ea similique quod quia officiis animi, rerum nemo, veritatis cum nesciunt! Quis ipsa et, temporibus tenetur explicabo, at error alias nobis doloremque culpa quod voluptas?
    Culpa adipisci natus similique eveniet dicta aspernatur tempora, optio ipsam? Laborum tenetur quia eum sunt quisquam hic eligendi odio velit assumenda necessitatibus, quaerat aut? Saepe, fugiat! Culpa illo suscipit corrupti.
    Itaque modi quisquam qui similique eligendi veritatis asperiores nulla, in officia ipsam amet neque doloribus tempore, aut illo dolorum? Fugiat quas, nesciunt aperiam ut consequuntur ipsum maxime rem facilis minima.
    Modi alias, distinctio iure dignissimos id sit ut consequuntur optio a debitis possimus nam molestias nobis quas laudantium, perspiciatis, deleniti labore magni ullam! Officiis consequatur, sit temporibus dolores eaque reprehenderit?
    Nisi, eligendi. Obcaecati ab ea minima ratione veniam deserunt rerum voluptatem voluptate tempore vel excepturi possimus ad adipisci eaque expedita eos tempora, amet quisquam tenetur quod ipsum labore. Voluptates, odit.
    Saepe sint porro a ullam esse accusamus nulla maiores. Nam autem veritatis, itaque cumque culpa distinctio numquam eum corporis doloribus, velit doloremque facilis voluptatum perspiciatis iste repellendus, animi quaerat minus.
    Quaerat consequuntur numquam est quod vero quisquam magni laboriosam voluptatibus ratione. Error laboriosam saepe accusantium dolore minus, totam ipsam aliquid doloremque beatae optio reprehenderit molestias aspernatur possimus? Possimus, voluptas quod.
    Adipisci, necessitatibus. Unde sequi vitae consequatur deserunt optio repellendus architecto deleniti commodi, soluta dolorem cum sed voluptates reprehenderit. Dolore ab quae suscipit cupiditate rem amet cum doloribus vitae illum nihil.
    Iure hic vel quisquam laborum facere, quos, doloremque tempore nemo nisi veniam velit nobis nulla magnam eum blanditiis, repudiandae pariatur voluptas quo! Commodi assumenda non blanditiis quidem voluptatum similique mollitia!
    Provident ratione voluptatum corrupti assumenda eligendi est, nisi eius dignissimos iure soluta nemo totam doloremque? Illum in labore sunt ratione saepe iste, delectus architecto ex at qui, magni dolor alias?
    Soluta dolore magni minus dignissimos, temporibus fugit rerum excepturi, provident nam iure facere molestias perspiciatis, quos laudantium! Dolorum, maxime nisi quam, minus aut eius cum dignissimos aliquam officia laboriosam cupiditate.
    Ducimus dolore vitae corrupti eligendi autem. Error neque autem iusto vel suscipit cum voluptates tempore aut perspiciatis quidem ratione, omnis consectetur, nesciunt sapiente qui. Labore quos laborum error sequi obcaecati!
    Accusantium magni natus iure aut ipsa nihil incidunt voluptatem provident ea unde minus commodi placeat soluta quas odit deleniti nulla illo eum temporibus, fuga perspiciatis nobis cupiditate praesentium in! Cupiditate!
    Minus hic, sint distinctio veritatis non optio architecto repellendus modi quaerat dolorum officiis earum natus officia, deleniti reprehenderit consequatur! Earum aspernatur iste corrupti aliquam sequi placeat! Odio, tenetur quas. Sint.</Text></>
  );
}

export default Home
